# Conclusion
As many industries have made use of analytics in recent decades, baseball teams have devoted significant resources to analytics/sabermetrics departments. The "Moneyball" era ushered in a new era of player evaluation, increasingly driven by numbers and formulas. Awards voting has also evolved with time, with metrics like WAR showing a stronger correlation with MVP voting in recent years. As front offices have prioritized certain attributes, so have voters. Slugging Percentage+ is a strong example. As teams prioritize to drafting or signing of players who hit for power in recent decades, voters have mirrored this desire.

There are so many statistics that can be analyzed. A future direction of this project would be replication and expansion of current graphs and analyses to several other statistics. While I did not find a way to effectively incorporate Statcast statistics, I am very interested to see how these nascent metrics have correlated with awards voting. Expanding beyong awards voting, it would be fascinating to understand what metrics lead to draft picks and signings. For instance, which player statistics drive high salaries? Are there certain metrics that specific teams have rewarded more than others, and how has that worked out in terms of performance?

One of my main takeaways is that the data collection and processing can be much more nuanced than expected. While baseball statistics are comprehensive and generally widely available, they aren't always easy to access in bulk. In addition, key attributes may be spread across disparate datasets that do not have common keys, making it difficult to reliably join datasets together.
