# Data

## Description
To obtain year-end awards data, I downloaded a dataset from the Lahman Baseball database. The Lahman Baseball database was created by SABR (Society for American Baseball Research) member Sean Lahman. It contains individual player and team stats per year from 1871 through 2024. This data is available in downloadable .csv files or as a downloadable SQL database. The awards dataset contains 12,462 rows and 6 columns. The dataset contains the standard awards of Most Valuable player, Cy Young, Gold Glove, and Rookie of the Year. Awards given out on a more frequent basis such as Player of the Week, and year-end awards that are more subsidiary such as the Outstanding DH Award, Reliever of the Year Award, and MLB Players Choice Outstanding Pitcher are also included in the dataset. The standard year-end awards of Most Valuable Player and Cy Young are of interest, so the dataset was filtered for these awards. The Most Valuable player (MVP) denotes the player which is deemed to have contributed the most to the success to their team. The Cy Young Award is similar, but is limited to pitchers. While rare, a pitcher is able to win MVP. To note, while all-star could be a powerful award for understanding player evaluation, it is not a year-end award so it was excluded.

To obtain player statistics, the pybaseball library was used. This library scrape Baseball Reference, Baseball Savant, and Fangraphs, all reliable MLB statistics websites. The data of interest are aggregate statistics per player, per year. There are many columns of data. In my analyses, I selected several variables based on the significance and notoriety of a given statistic. I pulled statistics from 1911 and onward, since the first MVP was awarded in 1911. The first Cy Young was awarded in 1956. To note, I used this package instead of obtaining data from the source websites because many of these sites have limited access or ability to download significant datasets easily. However, I still cited the relevant source websites in the bibliography. For most years of data, I filtered for players who had at least 300 plate appearances and filtered for pitchers who had at least 40 qualified innings pitched. For years where there was a shortened season, I lowered the threshold for qualified appearances in accordance with the number of games played in that season. For example, the pandemic-shortened season of 2020 was only 60 games long for each team, so I lowered the thresholds to 80 plate appearances and 5 innings pitched.

Data processing was done in Python. The processing presented a challenge. There was not a common player identifier between the awards dataset and the player statistics dataset. I ended up using a finding a separate file that exists for translation between baseball statistics datasets. The WAR (Wins Above Replacement) leader flag is a calculated variable. It took quite a bit of processing to properly process and merge the flag into the dataset, mainly because requisite data points for aggregation lived in different datasets. Even with this processing, the dataset was not fully complete, so I manually adjusted records that remained incomplete.

Lastly, pitchers who won MVP were excluded from the MVP/WAR analysis. The batter dataset and pitcher datasets are separate and were not easy to combine, so I left them separate. I believe that excluding pitchers from that analysis is okay because pitchers rarely win MVP. Since 1956, there have only been 11 pitchers to win MVP, out of 138 total.

References  
pybaseball. (2023, September 8). *pybaseball 2.2.7*. PyPI. Retrieved December 8, 2025, from
https://pypi.org/project/pybaseball/  

Society for American Baseball Research. (2025, October 30). *Lahman Baseball Database*. SABR.
Retrieved December 8, 2025, from https://sabr.org/lahman-database/  
FanGraphs. (n.d.). *FanGraphs — Baseball Statistics and Analysis*. Retrieved December 8, 2025, from
https://www.fangraphs.com/  

Major League Baseball Advanced Media. (n.d.). *Statcast Search*. Retrieved December 8, 2025, from
https://baseballsavant.mlb.com/statcast_search  


## Missing value analysis
There were several MVP winners for which the WAR leader flag was not properly calculated (they displayed as NA instead of 0 or 1). I manually adjusted these records.
